### ISSUE TITLE
Jupyter-book build broken

### ISSUE THREAD

**Issue by boisgera** [ue12/python-numerique#10]
Used to work with the environment spec <https://github.com/boisgera/python-numerique/blob/master/requirements.txt>, doesn't work anymore. Seems to be an update of jupyter-book. The error is

    The Table of Contents file is malformed: toc is not a mapping: <class 'list'>
    You may need to migrate from the old format, using:

        jupyter-book toc migrate python-numerique-fork/notebooks/_toc.yml

This suggestion course of actions makes it work again AFAICT. The "new" jupyter-book version is 0.11.2

**Comment by parmentelat** [comment]
hi
I think this was fixed in the devel branch already
I just merged devel into master so there's both even now, and they both should be fine with the latest jupyter-book
tell me if not

**Comment by boisgera** [comment]
OK, it works.
