### ISSUE TITLE
Pandoc version

### ISSUE THREAD

**Issue by boisgera** [ue12/python-numerique#5]
Specify pandoc version to use ? So far, `make` in `notebooks` generates an early error for pandoc < 2.11.

(This is where a conda environment specification would come handy.)

**Comment by boisgera** [comment]
Wrong. Actually the pandoc version error is panflute dependent and since we apparently need panflute < 2.0 for ipypublish, we can't have pandoc 2.11 (but pandoc 2.9 will do). See # 6.

**Comment by parmentelat** [comment]
closing as a leftover of the migration to jupyter-book
see also #3 for more details
